# Generated by Django 3.0.8 on 2020-07-22 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0002_auto_20200722_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='RansomewareResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RansomewareTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=1000)),
                ('retweeted', models.BooleanField()),
                ('hashtags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=360), size=None)),
            ],
        ),
    ]
