# Generated by Django 3.0.8 on 2020-07-22 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0003_ransomewareresult_ransomewaretweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ransomewareresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
