# Generated by Django 3.0.8 on 2020-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0004_ransomewareresult_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermometerResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
