# Generated by Django 3.0.8 on 2020-08-10 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0005_thermometerresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermometerresults',
            name='ranking',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
