# Generated by Django 3.0.8 on 2020-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0006_auto_20200810_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RansomewareResult',
        ),
        migrations.DeleteModel(
            name='RansomewareTweet',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
