# Generated by Django 3.0.8 on 2020-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatthermometer', '0008_auto_20200813_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('current_average', models.IntegerField(default=0)),
                ('periods', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='tweetfrequency',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
